<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="MSI" failures="2" tests="2" name="Default test(failed)" time="0.168" errors="0" timestamp="2022-11-16T17:47:22 IST">
  <testcase classname="TestNGstudy.FailedTCExecution" name="TC8" time="0.014">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at TestNGstudy.FailedTCExecution.TC8(FailedTCExecution.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC8 -->
  <testcase classname="TestNGstudy.FailedTCExecution" name="TC6" time="0.114">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNGstudy.FailedTCExecution.TC6() didn&amp;apos;t finish within the time-out 100">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNGstudy.FailedTCExecution.TC6() didn't finish within the time-out 100
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC6 -->
  <testcase classname="TestNGstudy.FailedTCExecution" name="TC9" time="0.0">
    <ignored/>
  </testcase> <!-- TC9 -->
  <testcase classname="TestNGstudy.FailedTCExecution" name="TC10" time="0.0">
    <ignored/>
  </testcase> <!-- TC10 -->
  <testcase classname="TestNGstudy.FailedTCExecution" name="TC7" time="0.0">
    <ignored/>
  </testcase> <!-- TC7 -->
</testsuite> <!-- Default test(failed) -->
